### ISSUE TITLE
Plugin details page has bad links

### ISSUE THREAD

**Issue by fletchowns** [jenkinsci/greenballs-plugin#6]
On this page: https://wiki.jenkins-ci.org/display/JENKINS/Green+Balls

The "Jenkins job for Green Balls" points to https://buildhive.cloudbees.com/job/jenkinsci/job/greenballs-plugin/ which is a 404

The flatter links points to https://flattr.com/thing/19304/Green-Balls-Hudson-Plugin which is 410

**Comment by nfalco79** [comment]
I think the "Green Balls" job was been deleted due Cloudbees migration, I have recreate it again.
About the flatter link I don't know (never used).

**Comment by mbarrien** [comment]
I just updated the Jenkins job link to the new location. The flattr location was removed from the wiki in May 2015. This issue can probably be closed.
